#!/usr/bin/env python3
from pathlib import Path
R=Path('.')
main=R/'buildsrc/store-app/src/main/java/com/attendpro/store/MainActivity.kt'
s=main.read_text(encoding='utf-8')
def rep(a,b,n=1):
    global s
    if s.count(a)<n: raise SystemExit('missing patch anchor: '+a[:80])
    s=s.replace(a,b,n)
rep('    private val authenticatedPresenceAt = ConcurrentHashMap<String, Long>()\n','    private val authenticatedPresenceAt = ConcurrentHashMap<String, Long>()\n    // Updated only by authenticated Direct BLE/GATT callbacks; discovery alone never means connected.\n    private val directBleUiAckAt = ConcurrentHashMap<String, Long>()\n')
rep('''    private fun storeTemplateTitle1978(value: String = storeHomeTemplate1978()): String = when (value) {\n        "SECTIONS" -> t("الأقسام", "Sections")\n        "CLASSIC" -> t("الكلاسيكي", "Classic")\n        else -> t("الرئيسي", "Main")\n    }\n\n    private fun buildElegantUi() {\n        when (storeHomeTemplate1978()) {\n            "SECTIONS" -> buildStoreSectionsTemplate1978()\n            "CLASSIC" -> buildStoreMainTemplate1978(classic = true)\n            else -> buildStoreMainTemplate1978(classic = false)\n        }\n    }\n''','''    private fun storeTemplateTitle1978(value: String = storeHomeTemplate1978()): String = when (value) {\n        "SECTIONS" -> t("الأقسام", "Sections")\n        "CLASSIC" -> t("الكلاسيكي", "Classic")\n        "FOCUS" -> t("التركيز", "Focus")\n        else -> t("الرئيسي", "Main")\n    }\n\n    private fun buildElegantUi() {\n        when (storeHomeTemplate1978()) {\n            "SECTIONS" -> buildStoreSectionsTemplate1978()\n            "CLASSIC" -> buildUi()\n            "FOCUS" -> buildStoreMainTemplate1978(classic = true)\n            else -> buildStoreMainTemplate1978(classic = false)\n        }\n    }\n''')
rep('''        val ids = arrayOf("MAIN", "SECTIONS", "CLASSIC")\n        val labels = arrayOf(\n            t("الرئيسي — واجهة يومية مضغوطة", "Main — compact daily dashboard"),\n            t("الأقسام — وصول سريع للخدمات", "Sections — quick service access"),\n            t("الكلاسيكي — ترتيب تقليدي آمن وخفيف", "Classic — safe lightweight traditional layout")\n        )\n''','''        val ids = arrayOf("MAIN", "SECTIONS", "CLASSIC", "FOCUS")\n        val labels = arrayOf(\n            t("الرئيسي — واجهة يومية متوازنة", "Main — balanced daily dashboard"),\n            t("الأقسام — بطاقات مستقلة ووصول سريع", "Sections — service cards and quick access"),\n            t("الكلاسيكي — اللوحة الأصلية الكاملة", "Classic — original full dashboard"),\n            t("التركيز — حضور واتصال أكبر وأوضح", "Focus — larger attendance and connection panels")\n        )\n''')
rep('''            t("الخصوصية والبيانات", "Privacy and data") to { startActivity(Intent(this, com.attendpro.core.PrivacyDataActivity::class.java)) },\n            t("الإعدادات", "Settings") to { startActivity(Intent(this, StoreSettingsActivity::class.java)) },\n''','''            t("الخصوصية والبيانات", "Privacy and data") to { startActivity(Intent(this, com.attendpro.core.PrivacyDataActivity::class.java)) },\n            t("البحث عن تحديثات التطبيق", "Check for app updates") to {\n                DistributionUpdateManager.check(this, repo.serverUrl.ifBlank { DistributionUpdateManager.DEFAULT_SERVER }, "store", manual = true)\n            },\n            t("الإعدادات", "Settings") to { startActivity(Intent(this, StoreSettingsActivity::class.java)) },\n''')
rep('''    private fun ownerShortcutCatalog(): List<OwnerShortcut> = listOf(\n        OwnerShortcut("employees", "الموظفون وملفات التعرف"),\n''','''    private fun ownerShortcutCatalog(): List<OwnerShortcut> = listOf(\n        OwnerShortcut("all_settings", "جميع إعدادات مدير المحل"),\n        OwnerShortcut("employees", "الموظفون وملفات التعرف"),\n''')
rep('''        when (id) {\n            "employees" -> startActivity(Intent(this, StoreSettingsActivity::class.java))\n''','''        when (id) {\n            "all_settings" -> startActivity(Intent(this, StoreSettingsActivity::class.java))\n            "employees" -> startActivity(Intent(this, MainActivity::class.java)\n                .putExtra(EXTRA_EMPLOYEE_MANAGER, true)\n                .putExtra(EXTRA_STORE_ADMIN_SESSION, repo.issueStoreAdminSession()))\n''')
rep('''            addView(UiKit.subtitle(this@MainActivity, p,\n                "اختر الوظيفة مباشرة. ويمكنك تثبيت أي وظيفة تختارها كاختصار في الشاشة الرئيسية.").apply {\n''','''            addView(UiKit.subtitle(this@MainActivity, p,\n                "يمكنك فتح جميع إعدادات مدير المحل في شاشة واحدة، أو الدخول مباشرة إلى كل خيار على حدة. ويمكن تثبيت الخيارات المهمة كاختصارات في الرئيسية.").apply {\n''')
rep('.setTitle("إدارة المحل")\n','.setTitle("إعدادات مدير المحل")\n',1)
rep('''    private fun markDirectBleState(employeeId: String, connected: Boolean, message: String) {\n        val employee = repo.employees().firstOrNull { it.employeeId.equals(employeeId, true) } ?: return\n        val now = System.currentTimeMillis()\n        val previous = nearby[employeeId]\n        if (connected) {\n            repo.markCompanionLinked(employeeId, "Bluetooth BLE • ACK", now)\n            val channels = previous?.channelTimes.orEmpty().toMutableMap().apply { put("Bluetooth مباشر", now) }\n            nearby[employeeId] = NearbyPhone(now, previous?.rssi ?: -60, channels, previous?.deviceName.orEmpty(), previous?.gpsInsideAt ?: 0L)\n            val lastDirect = previous?.channelTimes?.get("Bluetooth مباشر") ?: 0L\n            if (now - lastDirect > 10_000L) repo.addPresenceEvent(PresenceEvent(employeeId=employeeId, employeeName=employee.displayName, timestampEpochMillis=now, channel="Bluetooth مباشر", rssi=previous?.rssi?:-60, details="اتصال GATT مشفر ومؤكد مع هاتف الموظف"))\n        }\n        if (::status.isInitialized) status.text = "$message — ${employee.displayName}"\n        refreshDashboard()\n    }\n''','''    private fun markDirectBleState(employeeId: String, connected: Boolean, message: String) {\n        val employee = repo.employees().firstOrNull { it.employeeId.equals(employeeId, true) } ?: return\n        val canonicalId = employee.employeeId\n        val now = System.currentTimeMillis()\n        val previous = nearby[canonicalId]\n        if (connected) {\n            directBleUiAckAt[canonicalId] = now\n            repo.markCompanionLinked(canonicalId, "Bluetooth BLE • ACK", now)\n            val channels = previous?.channelTimes.orEmpty().toMutableMap().apply { put("Bluetooth مباشر • ACK", now) }\n            nearby[canonicalId] = NearbyPhone(now, previous?.rssi ?: -60, channels, previous?.deviceName.orEmpty(), previous?.gpsInsideAt ?: 0L)\n            val lastDirect = previous?.channelTimes?.get("Bluetooth مباشر • ACK") ?: 0L\n            if (now - lastDirect > 10_000L) repo.addPresenceEvent(PresenceEvent(employeeId=canonicalId, employeeName=employee.displayName, timestampEpochMillis=now, channel="Bluetooth مباشر • ACK", rssi=previous?.rssi?:-60, details="اتصال GATT مشفر ومؤكد مع هاتف الموظف"))\n        } else {\n            directBleUiAckAt.remove(canonicalId)\n        }\n        if (::status.isInitialized) status.text = "$message — ${employee.displayName}"\n        refreshDashboard()\n    }\n''')
rep('''    private fun isAuthenticatedPresenceConnected(employeeId: String, now: Long = System.currentTimeMillis()): Boolean =\n        authenticatedPresenceAt[employeeId]?.let { it > 0L && now - it <= 12_000L } == true\n\n    private fun isEmployeeActuallyConnected(employeeId: String, now: Long = System.currentTimeMillis()): Boolean =\n        isAuthenticatedPresenceConnected(employeeId, now) || directBle.isConnected(employeeId) ||\n            isLanConnected(employeeId, now) || isServerPresenceConnected(employeeId, now)\n''','''    private fun isAuthenticatedPresenceConnected(employeeId: String, now: Long = System.currentTimeMillis()): Boolean =\n        authenticatedPresenceAt[employeeId]?.let { it > 0L && now - it <= 12_000L } == true\n\n    private fun isDirectBleUiConnected(employeeId: String, now: Long = System.currentTimeMillis()): Boolean {\n        if (directBle.isConnected(employeeId)) return true\n        val callbackAck = directBleUiAckAt[employeeId] ?: 0L\n        val transportAck = directBle.lastAckAt(employeeId)\n        return (callbackAck > 0L && now - callbackAck <= 15_000L) ||\n            (transportAck > 0L && now - transportAck <= 15_000L)\n    }\n\n    private fun directBleLastVisibleAck(employeeId: String): Long =\n        maxOf(directBleUiAckAt[employeeId] ?: 0L, directBle.lastAckAt(employeeId))\n\n    private fun isEmployeeActuallyConnected(employeeId: String, now: Long = System.currentTimeMillis()): Boolean =\n        isAuthenticatedPresenceConnected(employeeId, now) || isDirectBleUiConnected(employeeId, now) ||\n            isLanConnected(employeeId, now) || isServerPresenceConnected(employeeId, now)\n''')
s=s.replace('directBle.isConnected(e.employeeId) -> "Bluetooth ACK"','isDirectBleUiConnected(e.employeeId, now) -> "Bluetooth ACK"')
s=s.replace('if (directBle.isConnected(id)) add("Bluetooth BLE • ACK")','if (isDirectBleUiConnected(id, now)) add("Bluetooth BLE • ACK")')
s=s.replace('val directAckAge = directBle.lastAckAt(employee.employeeId).let { if (it > 0L) now - it else Long.MAX_VALUE }','val directAckAge = directBleLastVisibleAck(employee.employeeId).let { if (it > 0L) now - it else Long.MAX_VALUE }')
s=s.replace('directBle.lastAckAt(employee.employeeId).takeIf { it > 0L },','directBleLastVisibleAck(employee.employeeId).takeIf { it > 0L },')
s=s.replace('directBle.lastAckAt(employee.employeeId).let { it > 0L && now - it <= 11_000L } -> "Bluetooth ACK"','isDirectBleUiConnected(employee.employeeId, now) -> "Bluetooth ACK"')
s=s.replace('actuallyConnected.any { directBle.isConnected(it.employeeId) }','actuallyConnected.any { isDirectBleUiConnected(it.employeeId, now) }')
s=s.replace('if (directBle.isConnected(id)) add("Bluetooth GATT • ACK")','if (isDirectBleUiConnected(id, now)) add("Bluetooth GATT • ACK")')
main.write_text(s,encoding='utf-8')
settings=R/'buildsrc/store-app/src/main/java/com/attendpro/store/StoreSettingsActivity.kt'
t=settings.read_text(encoding='utf-8').replace('"اختر القسم الذي تحتاجه فقط. جميع التفاصيل القديمة ما زالت موجودة داخل «الإعدادات المتقدمة» في قائمة ⋮."','"هذه شاشة جميع إعدادات مدير المحل. اختر القسم المطلوب، أو افتح «الإعدادات المتقدمة» من قائمة ⋮ لعرض كل الخيارات التفصيلية القديمة."')
settings.write_text(t,encoding='utf-8')
for rel in ['buildsrc/store-app/build.gradle.kts','buildsrc/employee-app/build.gradle.kts']:
    p=R/rel;x=p.read_text(encoding='utf-8').replace('versionCode = 93','versionCode = 94').replace('versionName = "2.0.0-RC3"','versionName = "2.0.0-RC4"');p.write_text(x,encoding='utf-8')
p=R/'tools/check-guide-release-contract.py';x=p.read_text(encoding='utf-8').replace('EXPECTED_CODE = 93','EXPECTED_CODE = 94').replace('EXPECTED_NAME = "2.0.0-RC3"','EXPECTED_NAME = "2.0.0-RC4"').replace('RELEASE_NOTES_V2.0.0_RC3.md','RELEASE_NOTES_V2.0.0_RC4.md').replace('"versionCode 93"','"versionCode 94"');p.write_text(x,encoding='utf-8')
notes=(R/'RELEASE_NOTES_V2.0.0_RC3.md').read_text(encoding='utf-8').replace('2.0.0-RC3','2.0.0-RC4').replace('versionCode 93','versionCode 94')
notes+='''\n\n## RC4 final correction batch\n- Bluetooth Direct/GATT authenticated connection now appears in connected-device status even without Wi-Fi/Hotspot broadcasting. Discovery alone never counts as connected.\n- Home layouts: Main, Sections, Classic (original full dashboard), and Focus. Classic no longer duplicates Main.\n- Store Manager settings can be opened all together or one option at a time.\n- Check for app updates is available directly in the top three-dot menu.\n- Direct keeps the verified internal updater; Play keeps Play In-App Updates.\n- Protected pairing protocol files remain unchanged.\n'''
(R/'RELEASE_NOTES_V2.0.0_RC4.md').write_text(notes,encoding='utf-8')
check=(R/'FIELD_TEST_CHECKLIST_RC3.md').read_text(encoding='utf-8').replace('RC3','RC4').replace('2.0.0-RC3','2.0.0-RC4').replace('versionCode 93','versionCode 94')
check+='''\n\n## RC4 correction checks\n- [ ] Bluetooth only: after authenticated ACK, employee appears connected with Wi-Fi/Hotspot off.\n- [ ] Disconnect Bluetooth and verify stale connected state clears.\n- [ ] Switch Main / Sections / Classic / Focus without freeze or state loss.\n- [ ] Store Manager exposes all settings and individual options.\n- [ ] Top ⋮ menu exposes Check for app updates.\n'''
(R/'FIELD_TEST_CHECKLIST_RC4.md').write_text(check,encoding='utf-8')
wf=R/'.github/workflows/build-v2-rc2-play-compliance.yml';w=wf.read_text(encoding='utf-8')
w=w.replace('V2.0.0 RC3','V2.0.0 RC4').replace('v2-rc3','v2-rc4').replace('Verify RC3','Verify RC4').replace('Package RC3','Package RC4').replace('signed RC3','signed RC4')
w=w.replace('versionCode = 93','versionCode = 94').replace('versionName = "2.0.0-RC3"','versionName = "2.0.0-RC4"').replace('RELEASE_NOTES_V2.0.0_RC3.md','RELEASE_NOTES_V2.0.0_RC4.md').replace('FIELD_TEST_CHECKLIST_RC3.md','FIELD_TEST_CHECKLIST_RC4.md')
w=w.replace("versionCode='93' versionName='2.0.0-RC3'","versionCode='94' versionName='2.0.0-RC4'").replace('= "93"','= "94"')
for a,b in [('ATTEND-PRO-Employee-V2.0.0-RC3.apk','ATTEND-PRO-Employee-V2.0.0-RC4.apk'),('ATTEND-PRO-Employee-V2.0.0-RC3-Play.aab','ATTEND-PRO-Employee-V2.0.0-RC4-Play.aab'),('ATTEND-PRO-Store-V2.0.0-RC3.apk','ATTEND-PRO-Store-V2.0.0-RC4.apk'),('ATTEND-PRO-Store-V2.0.0-RC3-Play.aab','ATTEND-PRO-Store-V2.0.0-RC4-Play.aab'),('ATTEND-PRO-V2.0.0-RC3-SOURCE.zip','ATTEND-PRO-V2.0.0-RC4-SOURCE.zip'),('ATTEND-PRO-V2.0.0-RC3/','ATTEND-PRO-V2.0.0-RC4/'),('ATTEND-PRO V2.0.0-RC3','ATTEND-PRO V2.0.0-RC4'),('Version code: 93','Version code: 94'),('ATTEND-PRO-V2.0.0-RC3-SIGNED','ATTEND-PRO-V2.0.0-RC4-SIGNED'),('ATTEND-PRO-V2.0.0-RC3-TEST-REPORTS','ATTEND-PRO-V2.0.0-RC4-TEST-REPORTS')]: w=w.replace(a,b)
wf.write_text(w,encoding='utf-8')
print('RC4 patch applied')
