from pathlib import Path

client=Path('buildsrc/core/src/main/java/com/attendpro/core/CentralServerClient.kt')
s=client.read_text()
s=s.replace('data class ReceiverEmployee(val employeeId: String, val employeeName: String, val branchId: String, val lastSeenAt: Long)', '''data class ReceiverEmployee(val employeeId:String,val employeeName:String,val branchId:String,val lastSeenAt:Long,val enabled:Boolean=true,val pendingLink:Boolean=false)''')
needle='    fun receiverSendEmployeeMessage('
insert='''    fun receiverManagedEmployees(serverUrl:String,receiverId:String,secret:String):Result<List<ReceiverEmployee>> = runCatching { requireHttps(serverUrl); val o=request(serverUrl,"/api/v1/monitor/employees/manage-list","POST",JSONObject().apply{put("receiverId",receiverId);put("secret",secret)}); val a=o.optJSONArray("employees")?:JSONArray(); (0 until a.length()).map{i->val x=a.getJSONObject(i);ReceiverEmployee(x.optString("employeeId"),x.optString("employeeName"),x.optString("branchId","MAIN"),x.optLong("lastSeenAt",0L),x.optBoolean("enabled",true),x.optBoolean("pendingLink",false))} }
    fun receiverAddEmployee(serverUrl:String,receiverId:String,secret:String,employeeId:String,employeeName:String,branchId:String):Result<Unit> = runCatching { requireHttps(serverUrl);request(serverUrl,"/api/v1/monitor/employees/add","POST",JSONObject().apply{put("receiverId",receiverId);put("secret",secret);put("employeeId",employeeId);put("employeeName",employeeName);put("branchId",branchId)});Unit }
    fun receiverUpdateEmployee(serverUrl:String,receiverId:String,secret:String,employeeId:String,employeeName:String,branchId:String):Result<Unit> = runCatching { requireHttps(serverUrl);request(serverUrl,"/api/v1/monitor/employees/update","POST",JSONObject().apply{put("receiverId",receiverId);put("secret",secret);put("employeeId",employeeId);put("employeeName",employeeName);put("branchId",branchId)});Unit }
    fun receiverSetEmployeeEnabled(serverUrl:String,receiverId:String,secret:String,employeeId:String,enabled:Boolean):Result<Unit> = runCatching { requireHttps(serverUrl);request(serverUrl,"/api/v1/monitor/employees/status","POST",JSONObject().apply{put("receiverId",receiverId);put("secret",secret);put("employeeId",employeeId);put("enabled",enabled)});Unit }

'''
if 'fun receiverManagedEmployees' not in s:s=s.replace(needle,insert+needle)
client.write_text(s)

activity=Path('buildsrc/store-app/src/main/java/com/attendpro/store/ReportReceiverActivity.kt')
a=activity.read_text().replace('t("هاتف الإدارة والاستلام", "Management & Receiver Phone")','t("هاتف الاستلام وإدارة الموظفين", "Receiver & Employee Management Phone")').replace('t("إعدادات مدير المحل", "Store Manager settings")','t("إدارة الموظفين", "Employee management")')
start=a.find('        if (receiver.canManageStore) {');end=a.find('\n        root.addView(UiKit.card',start)
if start<0 or end<0:raise SystemExit('management card boundaries not found')
a=a[:start]+'''        if (receiver.canManageStore) {
            val management=UiKit.card(this,p,9)
            management.addView(UiKit.sectionLabel(this,p,t("إدارة الموظفين","Employee management")))
            management.addView(UiKit.subtitle(this,p,t("إضافة وتعديل وتفعيل الموظفين فقط. لا تشمل إعدادات المحل أو صلاحيات مالك النظام. ربط هاتف الموظف يبقى من جهاز المحل المعتمد.","Add, edit and enable employees only. Store settings and System Owner privileges are excluded. Employee phone pairing remains on the authorized Store device.")))
            management.addView(UiKit.button(this,p,t("فتح إدارة الموظفين","Open employee management")).apply{setOnClickListener{openEmployeeManagement()}})
            root.addView(management)
        }
'''+a[end:]
marker='    private fun editRemoteStoreSettings() {'
methods='''    private fun openEmployeeManagement(){if(receiver.serverUrl.isBlank()){editServerUrl();return};Thread{val r=CentralServerClient.receiverManagedEmployees(receiver.serverUrl,receiver.receiverId,receiver.secret);runOnUiThread{if(r.isFailure){info(t("إدارة الموظفين","Employee management"),r.exceptionOrNull()?.message?:t("تعذر جلب الموظفين","Unable to load employees"));return@runOnUiThread};val es=r.getOrThrow();val labels=mutableListOf(t("＋ إضافة موظف","＋ Add employee"));labels.addAll(es.map{e->"${e.employeeName} • ${e.employeeId} • "+if(!e.enabled)t("موقوف","Disabled")else if(e.pendingLink)t("بانتظار ربط الهاتف","Awaiting phone pairing")else t("نشط","Active")});AlertDialog.Builder(this).setTitle(t("إدارة الموظفين","Employee management")).setItems(labels.toTypedArray()){_,w->if(w==0)editManagedEmployee(null)else managedActions(es[w-1])}.setNegativeButton(t("إغلاق","Close"),null).show()}}.start()}
    private fun editManagedEmployee(e:CentralServerClient.ReceiverEmployee?){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,8,24,0)};val id=UiKit.field(this,p,t("رقم الموظف","Employee ID")).apply{setText(e?.employeeId.orEmpty());isEnabled=e==null};val name=UiKit.field(this,p,t("اسم الموظف","Employee name")).apply{setText(e?.employeeName.orEmpty())};val branch=UiKit.field(this,p,t("الفرع","Branch")).apply{setText(e?.branchId?:"MAIN")};box.addView(id);box.addView(name);box.addView(branch);val d=AlertDialog.Builder(this).setTitle(if(e==null)t("إضافة موظف","Add employee")else t("تعديل الموظف","Edit employee")).setView(box).setPositiveButton(t("حفظ","Save"),null).setNegativeButton(t("إلغاء","Cancel"),null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val eid=id.text.toString().trim();val n=name.text.toString().trim();val b=branch.text.toString().trim().ifBlank{"MAIN"};if(eid.isBlank()){id.error=t("رقم الموظف مطلوب","Employee ID is required");return@setOnClickListener};if(n.length<2){name.error=t("أدخل اسم الموظف","Enter employee name");return@setOnClickListener};Thread{val r=if(e==null)CentralServerClient.receiverAddEmployee(receiver.serverUrl,receiver.receiverId,receiver.secret,eid,n,b)else CentralServerClient.receiverUpdateEmployee(receiver.serverUrl,receiver.receiverId,receiver.secret,eid,n,b);runOnUiThread{if(r.isSuccess){d.dismiss();info(t("تم الحفظ ✓","Saved ✓"),if(e==null)t("تم إنشاء سجل الموظف. اربط هاتفه من جهاز المحل المعتمد.","Employee record created. Pair the phone from the authorized Store device.")else t("تم تحديث بيانات الموظف.","Employee details updated."))}else name.error=r.exceptionOrNull()?.message?:t("تعذر الحفظ","Unable to save")}}.start()}};d.show()}
    private fun managedActions(e:CentralServerClient.ReceiverEmployee){val x=mutableListOf(t("تعديل الاسم والفرع","Edit name and branch"),if(e.enabled)t("إيقاف الموظف","Disable employee")else t("تفعيل الموظف","Enable employee"));if(receiver.canMessageEmployees)x.add(t("إرسال رسالة","Send message"));AlertDialog.Builder(this).setTitle("${e.employeeName} • ${e.employeeId}").setItems(x.toTypedArray()){_,w->when(w){0->editManagedEmployee(e);1->setManagedEmployeeEnabled(e,!e.enabled);2->if(receiver.canMessageEmployees)composeRemoteEmployeeMessage(e)}}.setNegativeButton(t("إلغاء","Cancel"),null).show()}
    private fun setManagedEmployeeEnabled(e:CentralServerClient.ReceiverEmployee,enabled:Boolean){Thread{val r=CentralServerClient.receiverSetEmployeeEnabled(receiver.serverUrl,receiver.receiverId,receiver.secret,e.employeeId,enabled);runOnUiThread{if(r.isSuccess)info(t("تم التحديث ✓","Updated ✓"),if(enabled)t("تم تفعيل الموظف.","Employee enabled.")else t("تم إيقاف الموظف إداريًا دون حذف بيانات الاقتران.","Employee administratively disabled without deleting pairing data."))else info(t("تعذر التحديث","Update failed"),r.exceptionOrNull()?.message?:t("خطأ","Error"))}}.start()}

'''
if 'private fun openEmployeeManagement()' not in a:a=a.replace(marker,methods+marker)
activity.write_text(a)
print('V122 employee-only management patch applied')
